title: "Grier Wenzel"
email: grierwenzel@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 My personal home for the exploration of code and new projects! Pleasure to meet you.
baseurl: "/" 
url: "/arinethu.github.io" 

github_username:  arinethu

sass:
  sass_dir: _sass

icon: ./assets/img/download20201200121743.png

theme: jekyll-theme-cayman